# Generated by Django 6.0.3 on 2026-04-21 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_session_date_alter_exercise_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
